[versions]
androidPlugins = "8.1.0-beta01"
androidxActivity = "1.7.1"
androidxComposeBom = "2023.05.00"
androidxComposeCompiler = "1.4.7"
androidxCore = "1.10.0"
androidxSplashScreen = "1.0.1"
androidxEspresso = "3.5.1"
androidxTestExt = "1.1.5"
coil = "2.3.0"
fuel = "3.0.0-SNAPSHOT"
moshi = "1.14.0"
kotlin = "1.8.21"
kotlinxCoroutines = "1.6.4"
kotlinxDatetime = "0.4.0"
reimaginedNavigation = "1.4.0"
jsoup = "1.16.1"
junit4 = "4.13.2"
spotless = "6.18.0"
turbine = "0.12.3"
composeMetrics = "1.0.0"
ksp = "1.8.21-1.0.11"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-windowSizeClass = {group = "androidx.compose.material3", name = "material3-window-size-class"}
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling"}
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxSplashScreen" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
fuel-moshi-jvm = { group = "com.github.kittinunf.fuel", name="fuel-moshi-jvm", version.ref = "fuel" }
fuel = { group = "com.github.kittinunf.fuel", name="fuel", version.ref = "fuel" }
olshevski-navigation-reimagined = { group = "dev.olshevski.navigation", name = "reimagined-material3", version.ref = "reimaginedNavigation" }
moshi-kotlin-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidPlugins" }
android-library = { id = "com.android.library", version.ref = "androidPlugins" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
compose-compiler-metrics = { id = "dev.shreyaspatil.compose-compiler-report-generator", version.ref = "composeMetrics" }
